### ISSUE TITLE
插件内获取角色方法和控制人物无法生效的问题

### ISSUE THREAD

**Issue by chengducode** [utmhikari/UnrealHttpServer#1]
![image](https://user-images.githubusercontent.com/36447282/114853591-869f7b80-9e16-11eb-861c-ae4ffad2f5c3.png)
![image](https://user-images.githubusercontent.com/36447282/114853643-94ed9780-9e16-11eb-9f1f-e9de9e32a055.png)

**Comment by utmhikari** [comment]
获取了editor的world
换worldcontext的索引或者用standalone可解决
